# Generated by Django 5.0.4 on 2024-05-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='commune',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='firstName',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='lastName',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='wilaya',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
